# YAML Configuration for CurrentFileScanner
# This file contains configuration settings for the CurrentFileScanner application.
# The settings control the behavior of directory scanning, including the default path,
# file name, status interval, spinner messages, and exception handling.


default_path: "/"
file_name: "sample.py"
status_interval: 10
spinner_messages:
  counting: "Counting directories"
  scanning: "Scanning directories"
handle_exceptions: true
